# site settings

title: Asmaa Hadir | Computer Scientist & AI Engineer
description: Portfolio and Blog website for Asmaa
taglong: Find Asmaa's thoughts and work here
tagshort: Asmaa's site
url: https://asmaamhadir.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/asmaamhadir/asmaamhadir.github.io

# author settings

author:
  name: Asmaa Hadir
  email: asmaamhadir99@gmail.com
photo: /assets/jpg/photo.png

# social media links

social:
  github: AsmaaMHadir
  linkedin: Asmaa Hadir
  twitter: AsmaaHadir51

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
